name: deploy

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sophies-personal-portfolio
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
